### ISSUE TITLE
undefined method `method_list' for nil:NilClass

### ISSUE THREAD

**Issue by mydoghasworms** [rdoc/rdoc#348]
When running `gem server` and trying to view rdoc for an installed gem (net-ldap-0.11, in my case), I get the following error page:

Error

While processing http://localhost:8808/doc_root/net-ldap-0.11/ the RDoc (4.2.0) server has encountered a NoMethodError exception:

undefined method `method_list' for nil:NilClass
Please report this to the RDoc issues tracker. Please include the RDoc version, the URI above and exception class, message and backtrace. If you're viewing a gem's documentation, include the gem name and version. If you're viewing Ruby's documentation, include the version of ruby.

Backtrace:

C:/Ruby193/lib/ruby/gems/1.9.1/gems/rdoc-4.2.0/lib/rdoc/store.rb:505:in `block in load_all'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rdoc-4.2.0/lib/rdoc/store.rb:500:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rdoc-4.2.0/lib/rdoc/store.rb:500:in `load_all'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rdoc-4.2.0/lib/rdoc/servlet.rb:182:in `documentation_source'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rdoc-4.2.0/lib/rdoc/servlet.rb:385:in `show_documentation'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rdoc-4.2.0/lib/rdoc/servlet.rb:125:in `do_GET'
C:/Ruby193/lib/ruby/1.9.1/webrick/httpservlet/abstract.rb:106:in `service'
C:/Ruby193/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
C:/Ruby193/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
C:/Ruby193/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'

**Comment by zzak** [comment]
Sorry about the label mishap..

So I'm thinking this might actually be a bug in the documentation of the gem, but I will need more time to look into it.
