### ISSUE TITLE
RDoc::Options#document raises NoMethodError

### ISSUE THREAD

**Issue by kyrylo** [rdoc/rdoc#352]
I'm following this guide: http://rdoc.rubyforge.org/RDoc/RDoc.html

When I execute `rdoc.document options` it raises:

```
NoMethodError: undefined method `delete_if' for nil:NilClass
--
0: /opt/rubies/druby-2.2.2/lib/ruby/2.2.0/rdoc/options.rb:449:in `check_files'
1: /opt/rubies/druby-2.2.2/lib/ruby/2.2.0/rdoc/options.rb:525:in `finish'
2: /opt/rubies/druby-2.2.2/lib/ruby/2.2.0/rdoc/rdoc.rb:462:in `document'
```

**Comment by zzak** [comment]
@kyrylo Can you share your `options`?

**Comment by kyrylo** [comment]
```ruby
[7] pry(main)> options = rdoc.load_options # returns an RDoc::Options instance
=> #<RDoc::Options:0x007f64417826c8
 @charset="UTF-8",
 @coverage_report=false,
 @dry_run=false,
 @encoding=#<Encoding:UTF-8>,
 @exclude=[],
 @files=nil,
 @force_output=false,
 @force_update=true,
 @generator=nil,
 @generator_name=nil,
 @generator_options=[],
 @generators={"darkfish"=>RDoc::Generator::Darkfish, "ri"=>RDoc::Generator::RI, "pot"=>RDoc::Generator::POT},
 @hyperlink_all=false,
 @line_numbers=false,
 @locale=nil,
 @locale_dir="locale",
 @locale_name=nil,
 @main_page=nil,
 @markup="rdoc",
 @op_dir=nil,
 @output_decoration=true,
 @page_dir=nil,
 @pipe=false,
 @rdoc_include=[],
 @root=#<Pathname:/home/kyrylo/code/fast_method_source>,
 @show_hash=false,
 @static_path=[],
 @stylesheet_url=nil,
 @tab_width=8,
 @template=nil,
 @template_dir=nil,
 @template_stylesheets=[],
 @title=nil,
 @update_output_dir=true,
 @verbosity=1,
 @visibility=:protected,
 @webcvs=nil,
 @write_options=false>

```

**Comment by drbrain** [comment]
You haven't told RDoc to document any files

**Comment by zzak** [comment]
This is likely true, you can do so by `options.rdoc_include << ["some", "files"]`.

Please let us know if this fixes your issue!

**Comment by kyrylo** [comment]
I'm not sure if this is still an issue, but I guess the main point was that the guide was misleading.
