### ISSUE TITLE
undefined method `singleton' for false:FalseClass

### ISSUE THREAD

**Issue by wimrijnders** [rdoc/rdoc#411]
Hi,

I recently installed ruby v.2.3.0 (using rvm). When I try to generate documentation with rdoc as usual, I now get the following:

```
undefined method `singleton' for false:FalseClass
Did you mean?  singleton_class
/home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/method_attr.rb:101:in `<=>'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/method_attr.rb:132:in `=='
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/method_attr.rb:132:in `see'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/method_attr.rb:114:in `documented?'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/stats.rb:162:in `block in doc_stats'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/stats.rb:162:in `count'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/stats.rb:162:in `doc_stats'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/stats.rb:122:in `calculate'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/stats.rb:367:in `summary'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/lib/rdoc/rdoc.rb:476:in `document'
        /home/wim/.rvm/gems/ruby-2.3.0/gems/rdoc-3.12.2/bin/rdoc:20:in `<top (required)>'
        /home/wim/.rvm/gems/ruby-2.3.0/bin/rdoc:23:in `load'
        /home/wim/.rvm/gems/ruby-2.3.0/bin/rdoc:23:in `<main>'
        /home/wim/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        /home/wim/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

```

I tried upgrading to most recent version of rdoc, but no change.
Any idea what I can do about this? Thanks,

Wim.

**Comment by wimrijnders** [comment]
OK figured it out; I was using sdoc, an unmaintained gem, which insisted on using rdoc v 3.12.2. Due to the upgrade to ruby v2.3.0 something broke.

I removed sdoc from my project and and using latest rdoc directly. Looks fine now.

Sorry to bother you with this.

**Comment by zzak** [comment]
Thanks for your follow up!

By the way, sdoc is still maintained and updated to support modern RDoc and
Ruby :)

If you run into any problems after upgrading, please report them here:
https://github.com/zzak/sdoc/issues/new
